"""empty message

Revision ID: 93f9553ec778
Revises: 79bf38da288f
Create Date: 2020-10-19 15:23:06.158326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f9553ec778'
down_revision = '79bf38da288f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=False))
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows_count')
    op.drop_column('Venue', 'past_shows_count')
    # ### end Alembic commands ###
